spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ume?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: 123456
  profiles:
    active: dev # 环境设置（dev test prod）

  application:
    name: ume-server  # nacos服务注册时的名称

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.103:8848

  # 返回json数据中的时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8080  # 端口


# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0


# 设置日志级别 ERROR, WARN, INFO(默认), DEBUG, ALL
logging:
  level:
    root: INFO
